// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;
using MorkoBotRavenEdition.Services;

namespace MorkoBotRavenEdition.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20180427094838_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-preview2-30571");

            modelBuilder.Entity("MorkoBotRavenEdition.Models.UserProfile", b =>
                {
                    b.Property<ulong>("Identifier")
                        .ValueGeneratedOnAdd();

                    b.Property<ushort>("Discriminator");

                    b.Property<int>("Experience");

                    b.Property<int>("ExperienceLevels");

                    b.Property<int>("ExperienceTarget");

                    b.Property<int>("Health");

                    b.Property<int>("OpenSewerTokens");

                    b.Property<string>("Username");

                    b.HasKey("Identifier");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("MorkoBotRavenEdition.Models.UserWarning", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DaysExpiry");

                    b.Property<string>("Reason");

                    b.Property<DateTime>("TimeAdded");

                    b.Property<ulong>("UserId");

                    b.HasKey("Id");

                    b.ToTable("UserWarnings");
                });
#pragma warning restore 612, 618
        }
    }
}
